services:
  postgres:
    image: postgres:17.4
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: hh-dev
      POSTGRES_PASSWORD: dev-password
      POSTGRES_DB: bloksh-db
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U hh-dev -d bloksh-db'" ]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - internal

  code-backend:
    image: code-backend
    container_name: bloksh-backend
    restart: always
    ports:
      - "8080:8080"
#      - "9092:9092"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bloksh-db
      SPRING_DATASOURCE_USERNAME: hh-dev
      SPRING_DATASOURCE_PASSWORD: dev-password
      SOCKETIO_PROTOCOL: ws
      LLM_KEY: ${LLM_KEY:-no-key}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - internal

  code-frontend:
    build:
      context: ./frontend
    container_name: bloksh-frontend
    restart: always
    networks:
      - internal

  nginx:
    image: nginx:1.27
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - code-backend
      - code-frontend
    networks:
      - internal

  liquibase:
    image: liquibase/liquibase:4.27
    container_name: liquibase-cli
    depends_on:
      - postgres
    volumes:
      - ./backend/src/main/resources/db/changelog:/liquibase/changelog:ro
    environment:
      - LIQUIBASE_COMMAND_URL=jdbc:postgresql://postgres:5432/bloksh-db
      - LIQUIBASE_COMMAND_USERNAME=hh-dev
      - LIQUIBASE_COMMAND_PASSWORD=dev-password
      - LIQUIBASE_COMMAND_CHANGELOG_FILE=db.changelog-master.yaml
    working_dir: /liquibase/changelog
    networks:
      - internal

networks:
  internal:

volumes:
  pgdata:
