services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: hh-dev
      POSTGRES_PASSWORD: dev-password
      POSTGRES_DB: bloksh-db
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U hh-dev -d bloksh-db'" ]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - internal

  code-backend:
    image: code-backend
    container_name: bloksh-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bloksh-db
      SPRING_DATASOURCE_USERNAME: hh-dev
      SPRING_DATASOURCE_PASSWORD: dev-password
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - internal

networks:
  internal:

volumes:
  pgdata: