package ru.hh.blokshnote.utility;

public enum WsMessageType {
  NEW_EDITOR_STATE,
  EDITOR_STATE_UPDATE,
  TEXT_SELECTION,
  CURSOR_POSITION,
  USER_ACTIVITY,
  LANGUAGE_CHANGE,
  TEXT_UPDATE,
  USERS_UPDATE,
}
