package ru.hh.blokshnote.utility;

public enum WsMessageType {
  NEW_EDITOR_STATE,
  TEXT_SELECTION,
  CURSOR_POSITION,
  USER_ACTIVITY,
  LANGUAGE_CHANGE,
  TEXT_UPDATE,
  USERS_UPDATE,
  NEW_COMMENT,
  CLOSE_ROOM,
  OPEN_ROOM,
  NEW_EDITOR_STATE_SEND_ALL,
  TEXT_UPDATE_SEND_ALL,
  LLM_STATUS
}
