name: Test
on:
  pull_request:
    branches: [ master ]

permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Make Maven wrapper executable
        run: chmod +x backend/mvnw

      - name: Run backend unit tests
        working-directory: backend
        run: ./mvnw test
